### ISSUE TITLE
Needs update; mostly concerning Unhappiness tooltip

### ISSUE THREAD

**Issue by UndeadDevel** [adaneslavo/List-Enhancements-for-VP#1]
Since there have been many changes to the way Happiness works in VP since the last List-Enhancements-for-VP update, many VP Lists have been changed; it's probably a good idea to check the entire mod thoroughly (I only checked it in a cursory manner) but one thing that is definitely broken now is the Unhappiness Tooltip. This particular issue is an easy fix, however:
line 198 - 279 of the file CityList.lua should simply be replaced with this one line, which will give all the relevant information:
`        local strOccupationTT = city:GetCityHappinessBreakdown() .. "[NEWLINE][NEWLINE]" .. city:GetCityUnhappinessBreakdown(false);`

**Comment by UndeadDevel** [comment]
Another note: the unhappiness value shown in the relevant column is, itself, wrong, as well (not just the tool tip). To fix it, lines 169-192 of CityList.lua need to be replaced with:
`        local iTotalUnhappiness = city:getHappinessDelta();`
This will use the current code to show the happiness difference (happiness - unhappiness); because of this, the tool tip there should probably be updated to be more accurate: line 47 of ListTextFields.xml could be changed to:
`			<Text>Sort by happiness difference</Text>`

**Comment by adaneslavo** [comment]
Just copied the solution updated on Civfanatics.
